version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Test FastAPI import
          command: |
            python -c "import fastapi"
            python -c "import pandas"
            python -c "import sklearn"

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t aiops-monitor .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
